# Generated by Django 4.2 on 2023-05-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
