# Generated by Django 4.2 on 2023-05-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_reviews_review_alter_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bot.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа'),
        ),
    ]
