# Generated by Django 4.2 on 2023-05-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_client_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
    ]
