# Generated by Django 4.2 on 2023-05-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.specialist', verbose_name='Cпециалист'),
        ),
    ]
