# Generated by Django 4.2 on 2023-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_slot_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(related_name='specialists', to='bot.service'),
        ),
    ]
